In [11]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [12]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
# Load from google drive
try:
    from google.colab import drive
    drive.mount('/content/drive')
    data_path = "/content/drive/MyDrive/data/cs7641/train_tokenized.csv"
    X_embeddings_path = "/content/drive/MyDrive/data/cs7641/X_embeddings.pq"
except:
    data_path = "../../data/train_tokenized.csv"
    X_embeddings_path = "../../data/X_embeddings.pq"

In [17]:
data = pd.read_csv(data_path) # Palash's file
data.drop(columns=["Unnamed: 0"], inplace=True)
data["full_text"] = data["full_text"].apply(lambda x: x.strip())
tasks = ["cohesion", "syntax", "vocabulary", "phraseology", "grammar", "conventions"]
data["holistic_score"] = data[tasks].mean(axis=1)
data

text_id                                          full_text  \
0     0016926B079C  I think that students would benefit from learn...   
1     0022683E9EA5  When a problem is a change you have to let it ...   
2     00299B378633  Dear, Principal\n\nIf u change the school poli...   
3     003885A45F42  The best time in life is when you become yours...   
4     0049B1DF5CCC  Small act of kindness can impact in other peop...   
...            ...                                                ...   
3906  FFD29828A873  I believe using cellphones in class for educat...   
3907  FFD9A83B0849  Working alone, students do not have to argue w...   
3908  FFDC4011AC9C  "A problem is a chance for you to do your best...   
3909  FFE16D704B16  Many people disagree with Albert Schweitzer's ...   
3910  FFED00D6E0BD  Do you think that failure is the main thing fo...   

      cohesion  syntax  vocabulary  phraseology  grammar  conventions  \
0          3.5     3.5         3.0          3.0      4.0          3.0   
1          2.5     2.5         3.0          2.0      2.0          2.5   
2          3.0     3.5         3.0          3.0      3.0          2.5   
3          4.5     4.5         4.5          4.5      4.0          5.0   
4          2.5     3.0         3.0          3.0      2.5          2.5   
...        ...     ...         ...          ...      ...          ...   
3906       2.5     3.0         3.0          3.5      2.5          2.5   
3907       4.0     4.0         4.0          4.0      3.5          3.0   
3908       2.5     3.0         3.0          3.0      3.5          3.0   
3909       4.0     4.5         4.5          4.0      4.5          4.5   
3910       3.5     2.5         3.5          3.0      3.0          3.5   

                                        word_token_nltk  \
0     ['I', 'think', 'that', 'students', 'would', 'b...   
1     ['When', 'a', 'problem', 'is', 'a', 'change', ...   
2     ['Dear', ',', 'Principal', 'If', 'u', 'change'...   
3     ['The', 'best', 'time', 'in', 'life', 'is', 'w...   
4     ['Small', 'act', 'of', 'kindness', 'can', 'imp...   
...                                                 ...   
3906  ['I', 'believe', 'using', 'cellphones', 'in', ...   
3907  ['Working', 'alone', ',', 'students', 'do', 'n...   
3908  ['``', 'A', 'problem', 'is', 'a', 'chance', 'f...   
3909  ['Many', 'people', 'disagree', 'with', 'Albert...   
3910  ['Do', 'you', 'think', 'that', 'failure', 'is'...   

                                             sent_token  \
0     ['I think that students would benefit from lea...   
1     ['When a problem is a change you have to let i...   
2     ['Dear, Principal\n\nIf u change the school po...   
3     ['The best time in life is when you become you...   
4     ['Small act of kindness can impact in other pe...   
...                                                 ...   
3906  ['I believe using cellphones in class for educ...   
3907  ['Working alone, students do not have to argue...   
3908  ['"A problem is a chance for you to do your be...   
3909  ['Many people disagree with Albert Schweitzer\...   
3910  ["Do you think that failure is the main thing ...   

                                      word_token_manual  \
0     ['I', 'think', 'that', 'students', 'would', 'b...   
1     ['When', 'a', 'problem', 'is', 'a', 'change', ...   
2     ['Dear,', 'Principal\n\nIf', 'u', 'change', 't...   
3     ['The', 'best', 'time', 'in', 'life', 'is', 'w...   
4     ['Small', 'act', 'of', 'kindness', 'can', 'imp...   
...                                                 ...   
3906  ['I', 'believe', 'using', 'cellphones', 'in', ...   
3907  ['Working', 'alone,', 'students', 'do', 'not',...   
3908  ['"A', 'problem', 'is', 'a', 'chance', 'for', ...   
3909  ['Many', 'people', 'disagree', 'with', 'Albert...   
3910  ['Do', 'you', 'think', 'that', 'failure', 'is'...   

                                             clean_text  \
0     ['think', 'students', 'would', 'benefit', 'lea...   
1     ['prob

In [18]:
X_embeddings = pd.read_parquet(X_embeddings_path)
X_embeddings

text_id         0         1         2         3         4  \
0     0016926B079C  0.050787 -0.020648  0.046628  0.042738  0.010770   
1     0022683E9EA5  0.029399  0.019760  0.072005  0.067443  0.005946   
2     00299B378633  0.021062 -0.020934 -0.001454  0.054375 -0.002969   
3     003885A45F42 -0.013444  0.030325  0.047811  0.081301  0.047056   
4     0049B1DF5CCC -0.009791  0.016098  0.013357  0.009807  0.077639   
...            ...       ...       ...       ...       ...       ...   
3906  FFD29828A873  0.007470  0.035424 -0.016566 -0.001752 -0.033487   
3907  FFD9A83B0849  0.015195  0.018013 -0.002546  0.015023 -0.007959   
3908  FFDC4011AC9C -0.015208 -0.028963  0.040175 -0.005345  0.070528   
3909  FFE16D704B16  0.017114  0.020061  0.001643 -0.011983  0.011232   
3910  FFED00D6E0BD -0.041802  0.045231  0.060647  0.073549  0.027274   

             5         6         7         8  ...       758       759  \
0    -0.037634 -0.001906 -0.021209 -0.022767  ... -0.038458 -0.057285   
1    -0.013700 -0.038997  0.015194 -0.002528  ... -0.041425 -0.012021   
2     0.022928 -0.031273  0.065228  0.025898  ... -0.011179 -0.035725   
3     0.012837 -0.009278  0.000785  0.037260  ... -0.018105  0.029301   
4     0.015961 -0.039515 -0.029869  0.000381  ...  0.020509 -0.037942   
...        ...       ...       ...       ...  ...       ...       ...   
3906 -0.029245 -0.003888 -0.034789  0.047848  ...  0.027962 -0.066315   
3907 -0.026204 -0.008703 -0.001500  0.011553  ...  0.015091 -0.086855   
3908  0.024906 -0.003196 -0.007841 -0.005557  ... -0.020075 -0.010158   
3909  0.031672  0.013890 -0.040182  0.012011  ...  0.009817 -0.032730   
3910 -0.024150 -0.025937  0.013207  0.017576  ... -0.050617  0.019914   

           760       761       762       763       764       765       766  \
0    -0.002004  0.036406 -0.018272  0.030892  0.050103 -0.033715  0.018629   
1    -0.030850  0.041491  0.016504 -0.009652  0.030991 -0.060080  0.021158   
2    -0.015828  0.026449  0.006725 -0.009515  0.063799 -0.014380 -0.005107   
3    -0.034215  0.056612  0.049250  0.027044  0.010883  0.046270 -0.001465   
4    -0.019292 -0.008364 -0.004770 -0.014046  0.062778  0.032312 -0.006859   
...        ...       ...       ...       ...       ...       ...       ...   
3906 -0.004833  0.017826  0.060797  0.019530  0.057516  0.019064  0.008649   
3907 -0.000405  0.036031 -0.010147  0.093431 -0.044508  0.073239  0.018504   
3908 -0.070796  0.040876  0.020430 -0.013329 -0.080693  0.006435  0.005327   
3909  0.027628  0.023874 -0.033760  0.010914  0.083385  0.005046 -0.057453   
3910 -0.011030  0.087014 -0.000313 -0.036353 -0.003646  0.004689  0.009332   

           767  
0    -0.060039  
1    -0.001554  
2    -0.016256  
3     0.036511  
4     0.019037  
...        ...  
3906 -0.014842  
3907 -0.018605  
3908  0.036601  
3909  0.038138  
3910  0.029274  

[3911 rows x 769 columns]

In [15]:
from utils_trans import mcrmse, mcrmse_error, mcrmse_scorer
from simple_models import SimpleGrader

In [19]:
y = data[tasks].values
X = X_embeddings.drop(columns=["text_id"]).values

In [22]:
# Create cross validation set
from sklearn.model_selection import cross_validate
from sklearn.base import TransformerMixin, BaseEstimator
from sklearn.metrics import mean_squared_error, make_scorer
from sklearn.model_selection import StratifiedKFold, train_test_split

from sklearn.ensemble import RandomForestRegressor

In [39]:
experiments = {
    "RandomForest300_20_7_3_0.2": {
        "decoder_cls": RandomForestRegressor,
        "decoder_kwargs": {
            "n_estimators": 300,
            "max_depth": 20,
            "min_samples_split": 7,
            "min_samples_leaf": 3,
            "max_features": 0.2
        }
    },
}
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv_iterators = skf.split(X=X, y=y.mean(axis=1).astype(int))
best_params = experiments["RandomForest300_20_7_3_0.2"]
models = []
y_preds = np.zeros((len(X), 6))
errs = []
for train_idx, test_idx in cv_iterators:
    model = SimpleGrader(best_params["decoder_cls"], best_params["decoder_kwargs"])
    model.fit(X=X[train_idx,:], y=y[train_idx,:])
    models.append(model)
    y_p = model.predict(X=X[test_idx,:])
    y_preds[test_idx, :] = y_p
    err = mcrmse_error(y_trues=y[test_idx,:], y_preds=y_p)
    errs.append(err)
    print("mcrmse: ", err)


/Users/kientran/opt/anaconda3/envs/trans/lib/python3.9/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


mcrmse:  0.5457328771196356
mcrmse:  0.5291294724129797
mcrmse:  0.5250191550938287
mcrmse:  0.530578751897442
mcrmse:  0.5515996805159926
mcrmse:  0.534406784462322
mcrmse:  0.5542293194609772
mcrmse:  0.5421176572995224
mcrmse:  0.5435312680841912
mcrmse:  0.5396423421167126


In [ ]:
import multiprocessing
class Process(multiprocessing.Process):
    def __init__(self, id):
        super(Process, self).__init__()
        self.id = id
                 
    def run(self):
        time.sleep(1)
        print("I'm the process with id: {}".format(self.id))

In [40]:
Y_pred = X_embeddings[["text_id"]]
for t in tasks:
    Y_pred[t] = 0
Y_pred.loc[:,tasks] = y_preds

/var/folders/yh/0ppzrrgs7m77v8rxlkjbf2540000gn/T/ipykernel_51776/4162937454.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y_pred[t] = 0
/var/folders/yh/0ppzrrgs7m77v8rxlkjbf2540000gn/T/ipykernel_51776/4162937454.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y_pred[t] = 0
/var/folders/yh/0ppzrrgs7m77v8rxlkjbf2540000gn/T/ipykernel_51776/4162937454.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instea

In [41]:
Y_pred.to_parquet("../../data/Y_pred_RF.pq")

In [36]:
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv_iterators = skf.split(X=X, y=y.mean(axis=1).astype(int))

In [37]:
next(cv_iterators)

/Users/kientran/opt/anaconda3/envs/trans/lib/python3.9/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


(array([   0,    1,    2, ..., 3908, 3909, 3910]),
 array([  15,   32,   38,   41,   65,   76,   94,   95,   96,  106,  114,
         115,  119,  149,  157,  163,  168,  171,  200,  206,  219,  223,
         237,  239,  243,  269,  296,  309,  314,  333,  336,  338,  352,
         353,  360,  366,  374,  392,  413,  446,  447,  457,  473,  475,
         477,  480,  492,  503,  527,  529,  531,  534,  536,  541,  547,
         549,  568,  579,  586,  587,  597,  603,  616,  631,  636,  639,
         645,  668,  673,  683,  701,  708,  716,  727,  739,  742,  773,
         799,  825,  830,  835,  836,  843,  881,  895,  897,  923,  926,
         927,  982,  983,  995,  996,  997, 1005, 1035, 1052, 1072, 1074,
        1077, 1084, 1086, 1088, 1103, 1108, 1115, 1152, 1154, 1178, 1184,
        1205, 1227, 1232, 1236, 1249, 1251, 1252, 1260, 1264, 1268, 1272,
        1277, 1282, 1290, 1298, 1301, 1305, 1345, 1364, 1367, 1380, 1384,
        1389, 1402, 1407, 1418, 1443, 1446, 1448, 1451, 1468,

In [30]:
c

(array([   0,    1,    2, ..., 3908, 3909, 3910]),
 array([   8,   11,   13,   48,   52,   60,   63,   74,   81,   85,   99,
         107,  108,  140,  144,  150,  153,  170,  202,  204,  218,  220,
         232,  234,  238,  247,  259,  268,  272,  279,  282,  283,  291,
         307,  326,  347,  355,  380,  381,  386,  391,  395,  398,  411,
         416,  427,  437,  450,  470,  491,  518,  520,  522,  530,  544,
         571,  574,  583,  589,  602,  608,  629,  650,  661,  672,  677,
         682,  689,  702,  707,  713,  717,  718,  722,  728,  730,  752,
         756,  759,  769,  775,  781,  783,  786,  787,  789,  809,  814,
         816,  855,  859,  865,  872,  877,  878,  880,  891,  901,  904,
         917,  920,  921,  922,  934,  935,  940,  944,  951,  955,  956,
         965,  969,  974,  976,  989,  998, 1004, 1019, 1022, 1024, 1034,
        1047, 1048, 1051, 1064, 1069, 1070, 1090, 1116, 1119, 1164, 1169,
        1170, 1179, 1180, 1191, 1212, 1224, 1238, 1243, 1248,

In [28]:
c[0].__len__()

3520

In [29]:
c[1].__len__()

391